DoAnWeb/Areas/Admin/Controllers/BookManagerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnWeb.Models;

namespace DoAnWeb.Areas.Admin.Controllers
{
    public class BookManagerController : Controller
    {
        private BookManagementEntities db = new BookManagementEntities();
        // GET: BookManager
        public ActionResult Index()
        {
            if (Session["user"] != null)
                return View(db.Books.ToList());
            else return RedirectToAction("Index", "Login");
        }

        public ActionResult Add(int? id)
        {
            if (Session["user"] == null) return RedirectToAction("Index", "Login");
            if (id == 1)
                ViewBag.Report = "Thêm Thành Công 1 Sách";
            else ViewBag.Report = "";
            var list = new SelectList(db.Categories.ToList(), "CateId", "CateName");
            ViewBag.Categories = list;
            list = new SelectList(db.Authors.ToList(), "AuthorId", "AuthorName");
            ViewBag.Authors = list;
            list = new SelectList(db.Publishers.ToList(), "PubId", "Name");
            ViewBag.Publishers = list;
            return View();
        }

        [HttpPost]
        public ActionResult Add(Book book, HttpPostedFileBase thumnail)
        {
            try
            {
                string thumnailName = "";
                string thumnailPath = "";
                if (thumnail != null)
                {
                    thumnailName = Path.GetFileName(thumnail.FileName);
                    thumnailPath = Path.Combine(Server.MapPath("~/Assest/Thumnail"), thumnailName);
                    thumnail.SaveAs(thumnailPath);
                    book.ImgUrl = thumnailName;
                }
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Add/1");
            }
            catch (Exception)
            {
                return RedirectToAction("Add/0");
            }
        }

        public ActionResult Edit(int id)
        {
            if (Session["user"] == null) return RedirectToAction("Index", "Login");
            Book book = null;
            var booksTemp = db.Books.Where(b => b.BookId == id).ToList();
            foreach (Book item in booksTemp)
            {
                book = item;
            }
            var list = new SelectList(db.Categories.ToList(), "CateId", "CateName");
            ViewBag.Categories = list;
            list = new SelectList(db.Authors.ToList(), "AuthorId", "AuthorName");
            ViewBag.Authors = list;
            list = new SelectList(db.Publishers.ToList(), "PubId", "Name");
            ViewBag.Publishers = list;
            return View(book);
        }

        [HttpPost]
        public ActionResult Edit(Book book, HttpPostedFileBase thumnail)
        {
            try
            {
                string thumnailName = "";
                string thumnailPath = "";
                if (thumnail != null)
                {
                    thumnailName = Path.GetFileName(thumnail.FileName);
                    thumnailPath = Path.Combine(Server.MapPath("~/Assest/Thumnail"), thumnailName);
                    thumnail.SaveAs(thumnailPath);
                    book.ImgUrl = thumnailName;
                }
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult Delete(int? id)
        {
            if (Session["user"] == null) return RedirectToAction("Index", "Login");
            if (id == null)
            {
                RedirectToAction("Index");
            }
            else
            {
                var book = db.Books.Find(id);
                db.Books.Remove(book);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Detail(int? id)
        {
            if (Session["user"] == null) return RedirectToAction("Index", "Login");
            var book = db.Books.Find(id);
            return View(book);
        }
    }
}

DoAnWeb/Areas/Admin/Views/BookManager/Add.cshtml
@model DoAnWeb.Models.Book

@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thêm Sách</h2>
<p style="color:darkgreen">@ViewBag.Report</p>
<div class="row" style="margin-bottom:30px">
    <div class="col">
        @Html.ActionLink("Về Lại Danh Sách", "Index")
    </div>
</div>

@using (Html.BeginForm("Add", "BookManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal row">
        <div class="col-1"></div>
        <div class="col-5">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Title, "Tiêu Đề", htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CateId, "Loại Sách", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CateId", (IEnumerable<SelectListItem>)ViewBag.Categories, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CateId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AuthorId, "Tác Giả", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("AuthorId", (IEnumerable<SelectListItem>)ViewBag.Authors, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.AuthorId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PubId, "Nhà Xuất Bản", htmlAttributes: new { @class = "control-label col-md-10" })
                <div class="col-md-10">
                    @Html.DropDownList("PubId", (IEnumerable<SelectListItem>)ViewBag.Publishers, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PubId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Summary, "Tóm Tắt", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextArea("Summary", new { htmlAttributes = new { @class = "form-control" }, @cols = "60", @rows = "7" })
                    @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm" class="btn btn-default" onclick="return IsEmptyInformationBook()" />
                </div>
            </div>
        </div>
        <div class="col-1"></div>
        <div class="col-5">

            <div class="form-group">
                @Html.LabelFor(model => model.Price, "Giá Tiền", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", type = "number", min = "0" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                S
                @Html.LabelFor(model => model.Quantity, "Số Lượng", htmlAttributes: new { @class = "control-label col-md-10" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", type = "number", min = "0" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreatedDate, "Ngày Xuất Bản", htmlAttributes: new { @class = "control-label col-md-10" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.CreatedDate, new { type = "date", @class = "form-control text-box single-line" })
                    @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ModifiedDate, "Ngày Tái Bản", htmlAttributes: new { @class = "control-label col-md-10" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.ModifiedDate, new { type = "date", @class = "form-control text-box single-line", onchange = "MinIsAnotherValue('CreatedDate','ModifiedDate','Ngày tái bản phải sau ngày sản xuất');" })
                    @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    @Html.LabelFor(model => model.IsActive, "Được Phép Bán", htmlAttributes: new { @class = "control-label col-md-4", style = "margin-left:-12px" })
                    @Html.CheckBoxFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        @Html.LabelFor(model => model.ImgUrl, "Ảnh Đại Diện", htmlAttributes: new { @class = "control-label col-md-12" })
                        <p class="col-md-10">
                            @*@Html.TextBoxFor(model=>model.ImgFile, "", new { type = "file", id = "thumnail",name= "ImgFile", onchange= "readURL(this)" })*@
                            <input type="file" id="thumnail" name="thumnail" onchange="readURL(this)" />
                        </p>
                    </div>
                    <div class="col">
                        <img id="canvasImg" style="width:129px; height:192px;" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/Scripts/jquery-3.3.1.js");
    @Scripts.Render("~/Scripts/Effect.js");
}

DoAnWeb/Areas/Admin/Views/BookManager/Detail.cshtml
@model DoAnWeb.Models.Book

@{
    ViewBag.Title = "Detail";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>@Model.Title</h2>
<hr />
<div class="row">

    <div class="col-1"></div>
    <div class="col-4">
        <dl class="dl-horizontal">
            <dd>
                <img src="~/Assest/Thumnail/@Model.ImgUrl" style="width:258px;height:384px">
            </dd>
        </dl>
    </div>
    <div class="col-6">
        <dl class="dl-horizontal">
            <h3>
                <dt>
                    @Html.DisplayName("Tác giả") :  @Html.DisplayFor(model => model.Author.AuthorName)
                </dt>
            </h3>
            <b>@Html.DisplayName("Mã Sách") : </b>@Html.DisplayFor(model => model.BookId)
            <b>@Html.DisplayName("Tóm Tắt") : </b>@Html.DisplayFor(model => model.Summary)
            <dd>
                @if (Model.IsActive == false)
                {
                    <i class="fas fa-exclamation-triangle" style="font-size:30px;color:red"></i>
                    <label style="font-size:40px;color:red">Ngừng Bán</label>
                }
                else
                {
                    <b>Giá Tiền : </b>
                    <label style="font-style:oblique; color:red; width:unset ;font-size:xx-large; text-transform:fullsize-kana">
                        @Html.DisplayFor(model => model.Price) VND
                    </label>
                }
            </dd>
            <dd>
                <b>Số Lượng : </b>@Html.DisplayFor(model => model.Quantity)
            </dd>

            <dd>
                <b>Ngày Xuất Bản : </b>@Model.CreatedDate.ToString("dd/MM/yyyy")
            </dd>
            <dd>
                <b>Ngày Tái Bản : </b>@Model.ModifiedDate.ToString("dd/MM/yyyy")
            </dd>
            <dd>
                <b>Thể Loại : </b>@Html.DisplayFor(model => model.Category.CateName)
            </dd>
            <dd>
                <b>Nhà Xuất Bản : </b>@Html.DisplayFor(model => model.Publisher.Name)
            </dd>
        </dl>
    </div>
    <div class="col-1"></div>
</div>


<p>
    @Html.ActionLink("Chỉnh Sửa", $"Edit", new { id = Model.BookId }) |
    @Html.ActionLink("Về Danh Sách Chính", "Index")
</p>
<script src="~/Scripts/jquery-3.3.1.js"></script>

DoAnWeb/Areas/Admin/Views/BookManager/Edit.cshtml
@model DoAnWeb.Models.Book

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Sửa Thông Tin Sách</h2>

@using (Html.BeginForm("Edit", "BookManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.BookId, new { @value = Model.BookId })
    @Html.HiddenFor(model => model.ImgUrl, new { @value = Model.ImgUrl })
    @Html.ValidationMessageFor(model => model.BookId, "", new { @class = "text-danger" })
    <div class="form-horizontal row">
        <div class="col-1">
        </div>
        <div class="col-5">
            <div class="form-group">
                @Html.LabelFor(model => model.Title, "Tiêu Đề", htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", value = Model.Title } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CateId, "Loại Sách", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CateId", (IEnumerable<SelectListItem>)ViewBag.Categories, htmlAttributes: new { @class = "form-control", value = Model.BookId })
                    @Html.ValidationMessageFor(model => model.CateId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AuthorId, "Tác Giả", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("AuthorId", (IEnumerable<SelectListItem>)ViewBag.Authors, htmlAttributes: new { @class = "form-control", value = Model.AuthorId })
                    @Html.ValidationMessageFor(model => model.AuthorId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PubId, "Nhà Xuất Bản", htmlAttributes: new { @class = "control-label col-md-10" })
                <div class="col-md-10">
                    @Html.DropDownList("PubId", (IEnumerable<SelectListItem>)ViewBag.Publishers, htmlAttributes: new { @class = "form-control", value = Model.PubId })
                    @Html.ValidationMessageFor(model => model.PubId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Summary, "Tóm Tắt", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextArea("Summary", new { htmlAttributes = new { @class = "form-control" }, @cols = "60", @rows = "7", @value = Model.Summary })
                    @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-1">
        </div>
        <div class="col-5">
            <div class="form-group">
                @Html.LabelFor(model => model.Price, "Giá Tiền", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", type = "number", min = "0", value = Model.Price } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, "Số Lượng", htmlAttributes: new { @class = "control-label col-md-10" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", type = "number", min = "0", value = Model.Quantity } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreatedDate, "Ngày Xuất Bản", htmlAttributes: new { @class = "control-label col-md-10" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.CreatedDate, "{0:yyyy-MM-dd}", new { type = "date"
                                                                           ,@class = "form-control text-box single-line"})
                    @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ModifiedDate, "Ngày Tái Bản", htmlAttributes: new { @class = "control-label col-md-10" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.ModifiedDate, "{0:yyyy-MM-dd}", new { type = "date"
                                                                                          , @class = "form-control text-box single-line"
                                                                                          , onchange = "MinIsAnotherValue('CreatedDate','ModifiedDate','Ngày tái bản phải sau ngày sản xuất');"
                                                                                          , min="0001-02-01"})
                    @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.CheckBoxFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        @Html.LabelFor(model => model.ImgUrl, "Ảnh Đại Diện", htmlAttributes: new { @class = "control-label col-md-12" })
                        <p class="col-md-10">
                            @*@Html.TextBoxFor(model=>model.ImgFile, "", new { type = "file", id = "thumnail",name= "ImgFile", onchange= "readURL(this)" })*@
                            <input type="file" id="thumnail" name="thumnail" onchange="readURL(this)" />
                        </p>
                    </div>
                    <div class="col">
                        <img id="canvasImg" style="width:129px; height:192px;" , src="~/Assest/Thumnail/@Model.ImgUrl" />
                    </div>
                </div>
            </div>

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sửa" class="btn btn-default" />
            </div>
        </div>

    </div>
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    @Scripts.Render("~/Scripts/Effect.js");
}
<div class="row" style="margin-bottom:30px">
    <div class="col">
        @Html.ActionLink("Về Lại Danh Sách", "Index")
    </div>
</div>

DoAnWeb/Areas/Admin/Views/BookManager/Index.cshtml
@model List<DoAnWeb.Models.Book>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@Styles.Render("~/bundles/adminTableCss")
<link href="../Content/dataTables.bootstrap4.css" rel="stylesheet">
<link href="~/Content/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="~/Scripts/v4-shims.js"></script>
<h2>Quản Lý Sách</h2>
<div>
    <div class="row">
        <div class="col-10"></div>
        <div class="fa fa-plus col-2">
            @Html.ActionLink("Thêm Sách", $"Add")
        </div>
    </div>
</div>
</div>
<div class="card-body">
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable">
            <thead>
                <tr role="row">
                    <th>Tiêu Đề</th>
                    <th>Loại Sách</th>
                    <th>Ảnh Đại Diện</th>
                    <th>Giá Tiền</th>
                    <th>Tổng Số Lượng</th>
                    <th>Trạng Thái</th>
                    <th>Lựa Chọn</th>
                </tr>
            </thead>
            <tbody>
                @foreach (DoAnWeb.Models.Book item in Model)
                {
                    <tr>
                        <td><a href="~/Books/Detail/@item.BookId">@item.Title</a></td>
                        <td>@item.Category.CateName</td>
                        <td><img src="~/Assest/Thumnail/@item.ImgUrl" style="width:129px;height:192px" /></td>
                        <td>@item.Price</td>
                        <td>@item.Quantity</td>
                        <td>@item.IsActive</td>
                        <td>
                            @*@Html.ActionLink("Sửa", $"Edit/{item.BookId}")|
                            <a href="BookManager/Delete/@item.BookId" onclick="return confirm('Bạn có muốn xóa @item.Title');">Xóa</a>|
                            <a href="~/Books/Detail/@item.BookId">Chi Tiết</a>*@
                            <a href="BookManager/Edit/@item.BookId">
                                <i class="fa fa-pencil" aria-hidden="true"></i>
                            </a>
                            <a href="BookManager/Detail/@item.BookId">
                                <i class="fa fa-eye" aria-hidden="true"></i>
                            </a>
                            <a href="BookManager/Delete/@item.BookId" onclick="return confirm('Bạn có muốn xóa @item.Title');">
                                <i class="fa fa-times" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>
@Scripts.Render("~/bundles/adminTableJs")
<script>
    $(document).ready(function () {
        $('#dataTable').DataTable();
    });
</script>