DoAnWeb/Models/Book.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Comments = new HashSet<Comment>();
            this.OrderBookDetails = new HashSet<OrderBookDetail>();
        }
    
        public int BookId { get; set; }
        public string Title { get; set; }
        public int CateId { get; set; }
        public int AuthorId { get; set; }
        public int PubId { get; set; }
        public string Summary { get; set; }
        public string ImgUrl { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Quantity { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBookDetail> OrderBookDetails { get; set; }
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}

DoAnWeb/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnWeb.Models;

namespace DoAnWeb.Controllers
{
    public class AuthorsController : Controller
    {
        private BookManagementEntities db = new BookManagementEntities();
        // GET: Client/Author
        public ActionResult Detail(int id)
        {
            LoginClientController login = new LoginClientController();
            login.ReadCookie();
            ViewBag.Cate = db.Categories.ToList();
            ViewBag.Books = db.Books.Where(b => b.AuthorId == id).ToList();
            Author author = db.Authors.Find(id);
            return View(author);
        }

        public ActionResult ListAuthor()
        {
            return View(db.Authors.ToList());
        }
    }
}

DoAnWeb/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnWeb.Models;

namespace DoAnWeb.Controllers
{
    public class BooksController : Controller
    {
        private BookManagementEntities db = new BookManagementEntities();
        // GET: Client/Books
        public ActionResult Index()
        {
            LoginClientController login = new LoginClientController();
            login.ReadCookie();
            ViewBag.Cate = db.Categories.ToList();
            return View(db.Books.ToList());
        }

        public ActionResult Detail(int id)
        {
            LoginClientController login = new LoginClientController();
            login.ReadCookie();
            ViewBag.Cate = db.Categories.ToList();
            Book book = db.Books.Find(id);
            return View(book);
        }

        public ActionResult SearchByCate(int id, int page)
        {
            LoginClientController login = new LoginClientController();
            login.ReadCookie();
            List<Book> books = db.Books.Where(b => b.CateId == id).OrderBy(b => b.BookId).Skip(36 * (page - 1)).Take(36).ToList();
            ViewBag.Cate = db.Categories.ToList();
            ViewBag.CateName = db.Categories.ToList().Find(c => c.CateId == id).CateName;
            ViewBag.PageIndex = page;
            return View(books);
        }

        [HttpPost]
        public ActionResult SearchByName(string name, int page)
        {
            LoginClientController login = new LoginClientController();
            login.ReadCookie();
            if (!name.Replace(" ", "").Equals(""))
            {
                List<Book> books = db.Books.Where(b => b.Title.Contains(name)).OrderBy(b => b.BookId).Skip(36 * (page - 1)).Take(36).ToList();
                ViewBag.Cate = db.Categories.ToList();
                ViewBag.SearchKey = name;
                ViewBag.PageIndex = page;
                return View(books);
            }
            else return RedirectToAction("Index");
        }

        [HttpPost]
        public PartialViewResult GetSearchResult(string search)
        {
            if (!search.Replace(" ", "").Equals(""))
            {
                ViewBag.Books = db.Books.Where(b => b.Title.Contains(search)).ToList();
                ViewBag.Authors = db.Authors.Where(a => a.AuthorName.Contains(search)).ToList();
            }
            return PartialView();
        }

        public ActionResult GetBooksCards(List<Book> books, int? isSmall)
        {
            if (isSmall != null)
                ViewBag.IsSmall = 1;
            return PartialView(books);
        }
    }
}

DoAnWeb/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnWeb.Models;

namespace DoAnWeb.Controllers
{
    public class CommentController : Controller
    {
        private BookManagementEntities db = new BookManagementEntities();
        // GET: Client/Comment
        public ActionResult ShowComment(int id)
        {
            List<Comment> comments = db.Comments.Where(c => c.BookId == id && c.IsActive == true)
                                                .OrderByDescending(c => c.CommentId)
                                                .ToList();
            ViewBag.BookId = id;
            return View(comments);
        }
        [HttpPost]
        public ActionResult Add(string content, int bookId)
        {
            Comment comment = new Comment
            {
                Content = content,
                Username = Session["userClient"].ToString(),
                CreatedDate = DateTime.Now,
                BookId = bookId,
                IsActive = true
            };
            db.Comments.Add(comment);
            db.SaveChanges();
            return RedirectToAction($"../Books/Detail/{bookId}");
        }

        public ActionResult Delete(int id)
        {
            Comment comment = db.Comments.ToList().Find(c => c.CommentId == id);
            try
            {
                comment.IsActive = false;
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
            }
            catch (Exception)
            {
            }
            return RedirectToAction($"../Books/Detail/{comment.BookId}");
        }
    }
}

DoAnWeb/Controllers/PopularContentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnWeb.Models;

namespace DoAnWeb.Controllers
{
    public class PopularContentController : Controller
    {
        private BookManagementEntities db = new BookManagementEntities();
        // GET: Client/PopularContent
        public ActionResult GetBookByAuthor(int AuthorId, int BookId)
        {
            List<Book> books = db.Books.Take(4).Where(b => b.AuthorId == AuthorId && b.BookId != BookId).ToList();
            return View(books);
        }

        public ActionResult GetBookByNewest()
        {
            List<Book> books = db.Books.Take(6).OrderByDescending(b => b.BookId).ToList();
            return View(books);
        }

        public ActionResult NewestBook(int id)
        {
            if (id < 1) id = 1;
            List<Book> books = db.Books.OrderByDescending(b => b.BookId).Skip(6 * (id - 1)).Take(6).ToList();
            ViewBag.Cate = db.Categories.ToList();
            ViewBag.PageIndex = id;
            return View(books);
        }

        public ActionResult GetBookByPopularest()
        {
            List<SumValueByBookOrderDetail> sumValues = db.OrderBookDetails.GroupBy(d => d.BookId)
                                                     .SelectMany(cs => cs.Select(
                                                         csLine => new SumValueByBookOrderDetail
                                                         {
                                                             BookId = csLine.BookId,
                                                             SumQuantity = cs.Sum(c => c.Quantity)
                                                         })).Take(6).ToList();
            List<int> sumQuantity = sumValues.Select(sq => sq.BookId).ToList();
            List<Book> books = db.Books.Where(b => sumQuantity.Contains(b.BookId)).ToList();
            return View(books);
        }

        public ActionResult PopularestBook(int id)
        {
            if (id < 1) id = 1;
            List<SumValueByBookOrderDetail> sumValues = db.OrderBookDetails.GroupBy(d => d.BookId)
                                                     .SelectMany(cs => cs.Select(
                                                         csLine => new SumValueByBookOrderDetail
                                                         {
                                                             BookId = csLine.BookId,
                                                             SumQuantity = cs.Sum(c => c.Quantity)
                                                         })).OrderBy(b => b.SumQuantity).Skip(36 * (id - 1)).Take(36).ToList();
            List<int> sumQuantity = sumValues.Select(sq => sq.BookId).ToList();
            List<Book> books = db.Books.Where(b => sumQuantity.Contains(b.BookId)).ToList();
            ViewBag.Cate = db.Categories.ToList();
            ViewBag.PageIndex = id;
            return View(books);
        }

        public ActionResult SearchByCate(int id)
        {
            if (id < 1) id = 1;
            LoginClientController login = new LoginClientController();
            login.ReadCookie();
            List<Book> books = db.Books.Where(b => b.CateId == id).Take(6).ToList();
            ViewBag.Cate = db.Categories.ToList();
            ViewBag.CateName = db.Categories.ToList().Find(c => c.CateId == id).CateName;
            return View(books);
        }
    }
}

DoAnWeb/Controllers/PublisherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnWeb.Models;

namespace DoAnWeb.Controllers
{
    public class PublisherController : Controller
    {
        // GET: Publisher
        BookManagementEntities db = new BookManagementEntities();
        public ActionResult ListPublisher()
        {
            return View(db.Publishers.ToList());
        }
    }
}

DoAnWeb/Views/Books/Detail.cshtml
@model DoAnWeb.Models.Book

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<h2>@Model.Title</h2>
<hr />
<div class="row">
    <div class="col-md-10">
        <div class="row">
            <div class="col-1"></div>
            <div class="col-4">
                <dl class="dl-horizontal">
                    <dd>
                        <img src="~/Assest/Thumnail/@Model.ImgUrl" ) style="width:258px;height:384px">
                    </dd>
                </dl>
            </div>
            <div class="col-6">
                <dl class="dl-horizontal">
                    <h3>
                        <dt>
                            @Html.DisplayName("Tác giả") :  <a href="~/Authors/Detail/@Model.AuthorId">@Model.Author.AuthorName</a>
                        </dt>
                    </h3>
                    <b>@Html.DisplayName("Tóm Tắt") : </b>@Html.DisplayFor(model => model.Summary)
                    <dd>
                        @if (Model.IsActive == false)
                        {
                            <i class="fas fa-exclamation-triangle" style="font-size:30px;color:red"></i>
                            <label style="font-size:40px;color:red">Ngừng Bán</label>
                        }
                        else
                        {
                            <b>Giá Tiền : </b>
                            <label style="font-style:oblique; color:red; width:unset ;font-size:xx-large; text-transform:fullsize-kana">
                                @Html.DisplayFor(model => model.Price) VND
                            </label>
                            <div class="row">
                                @using (Ajax.BeginForm("../Order/PushCart", new AjaxOptions
                                {
                                    HttpMethod = "POST",
                                    InsertionMode = InsertionMode.Replace,
                                    UpdateTargetId = "update-me"
                                }))
                                {
                                    int defaultQuantity = 1;
                                    <table style="margin-left:15px">
                                        <tr>
                                            <td><b>Số Lượng: </b></td>
                                            <td>
                                                <input type="number" name="Quantity" class="form-control col-6" max="@Model.Quantity" , min="1" , Style="margin-left:20px" value="1" />
                                                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                                                @Html.HiddenFor(model => model.BookId, new { @value = Model.BookId })
                                                @Html.ValidationMessageFor(model => model.BookId, "", new { @class = "text-danger" })
                                                @Html.HiddenFor(model => model.Price, new { @value = Model.Price })
                                                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                            </td>
                                            <td>
                                                <button type="submit" class="btn btn-danger">
                                                    <i class="glyphicon glyphicon-refresh fas fa-cart-plus"></i>
                                                    Thêm Vào Giỏ
                                                </button>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td></td>
                                            <td><div id="update-me" class="row"></div></td>
                                        </tr>
                                    </table>
                                }

                            </div>
                        }
                    </dd>
                    <dd>
                        <b>Số Lượng Trong Kho : </b>@Model.Quantity
                    </dd>
                    <b>Ngày Xuất Bản : </b>@Model.CreatedDate.ToString("dd/MM/yyyy")
                    </dd>
                    <dd>
                        <b>Ngày Tái Bản : </b>@Model.ModifiedDate.ToString("dd/MM/yyyy")
                    </dd>
                    <dd>
                        <b>Thể Loại : </b>@Html.DisplayFor(model => model.Category.CateName)
                    </dd>
                    <dd>
                        <b>Nhà Xuất Bản : </b>@Html.DisplayFor(model => model.Publisher.Name)
                    </dd>
                </dl>
            </div>
            <div class="col-1"></div>
        </div>
        <div class="row">
            <div class="col-1"></div>
            <div class="col-10">
                @{
                    Html.RenderAction("ShowComment", "Comment", new { id = Model.BookId });
                }
            </div>
            <div class="col-1"></div>
        </div>
    </div>
    <div class="col-md-2">
        @{
            Html.RenderAction("GetBookByAuthor", "PopularContent", new { AuthorId = Model.AuthorId, BookId = Model.BookId });
        }
    </div>
</div>
<p class="text-center">
    @Html.ActionLink("Về Danh Sách Chính", "Index")
</p>
<script src="~/Scripts/jquery-3.3.1.js"></script>
@Scripts.Render("~/bundles/ajax")

DoAnWeb/Views/Books/GetSearchResult.cshtml
<div id="ddlAjax">
    <div class="dropdown-header col-10">Tác Giả</div>
    @{
        if (ViewBag.Authors != null)
        {
            var maxCountAuthor = 0;
            if (ViewBag.Authors.Count > 3)
            { maxCountAuthor = 3; }
            else { maxCountAuthor = ViewBag.Authors.Count; }
            for (int i = 0; i < maxCountAuthor; i++)
            {
                <a class="dropdown-item col-10" href="~/Authors/Detail/@ViewBag.Authors[i].AuthorId">@ViewBag.Authors[i].AuthorName</a>
            }
        }
    }
    <div class="dropdown-header col-10">Sách</div>
    @{
        if (ViewBag.Books != null)
        {
            var maxCountBooks = 0;
            if (ViewBag.Books.Count > 5)
            { maxCountBooks = 5; }
            else { maxCountBooks = ViewBag.Books.Count; }
            for (int i = 0; i < maxCountBooks; i++)
            {
                <a class="dropdown-item col-10" href="~/Books/Detail/@ViewBag.Books[i].BookId">@ViewBag.Books[i].Title</a>
            }
        }
    }
</div>

DoAnWeb/Views/Books/Index.cshtml
@model List<DoAnWeb.Models.Book>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class="menu-slider-header">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="left-sidebar-header">
                    <a>
                        Danh Mục
                        <i class="fa fa-list" aria-hidden="true"></i>
                    </a>
                </div>
                <div class="left-sidebar-content">
                    <ul>
                        <li>
                            <a href="#">
                                Thể loại
                                <i class="fa fa-plus" aria-hidden="true"></i>
                            </a>
                            <div class="sub-menu">
                                <ul>
                                    <li class="sub-menu-title">
                                        <h2>Thể loại</h2>
                                    </li>
                                    @foreach (var item in ViewBag.Cate)
                                    {
                                        <li>
                                            <a href="~/Books/SearchByCate/@item.CateId/1">
                                                @item.CateName
                                            </a>
                                        </li>
                                    }
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a href="#">
                                Tác giả
                                <i class="fa fa-plus" aria-hidden="true"></i>
                            </a>
                            <div class="sub-menu">
                                <ul>
                                    <li class="sub-menu-title">
                                        <h2>Tác giả</h2>
                                    </li>
                                    @{Html.RenderAction("ListAuthor", "Authors");}
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a href="#">
                                Nhà xuất bản
                                <i class="fa fa-plus" aria-hidden="true"></i>
                            </a>
                            <div class="sub-menu">
                                <ul>
                                    <li class="sub-menu-title">
                                        <h2>Nhà xuất bản</h2>
                                    </li>
                                    @{Html.RenderAction("ListPublisher", "Publisher");}
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="left-sidebar-banner">
                    <a>
                        <img src="~/Assest/Thumnail/sach-tiki.jpg" />
                    </a>
                </div>
            </div>
            <div class="col-md-9">
                <div class="right-sidebar-header">
                    <ul>
                        <li><a href="#">Trang chủ</a></li>
                        <li><a href="#">Sản Phẩm</a></li>
                        <li><a href="#">Giới thiệu</a></li>
                        <li><a href="#">Liên hệ</a></li>
                    </ul>
                </div>
                <div class="right-sidebar-content">
                    <div id="myCarousel" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                            <li data-target="#myCarousel" data-slide-to="1"></li>
                            <li data-target="#myCarousel" data-slide-to="2"></li>
                            <li data-target="#myCarousel" data-slide-to="3"></li>
                            <li data-target="#myCarousel" data-slide-to="4"></li>
                            <li data-target="#myCarousel" data-slide-to="5"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="item active">
                                <img src="~/Assest/Thumnail/bannerfhs-V2.jpg" style="width:100%">
                            </div>

                            <div class="item">
                                <img src="~/Assest/Thumnail/ChuNhat-W1-915x423.jpg" style="width:100%">
                            </div>

                            <div class="item">
                                <img src="~/Assest/Thumnail/Death-915x423-V2.jpg" style="width:100%">
                            </div>
                            <div class="item">
                                <img src="~/Assest/Thumnail/Haruki-Murakami-915x423-1.jpg" style="width:100%">
                            </div>
                            <div class="item">
                                <img src="~/Assest/Thumnail/QV-915x423.jpg" style="width:100%">
                            </div>
                            <div class="item">
                                <img src="~/Assest/Thumnail/The-Best-Books-of-2018-915x423.jpg" style="width:100%">
                            </div>
                        </div>
                        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="banner-top">
        <div class="row m-pad-top-10">
            <div class="fhs-banner-image-block" style="">
                <div class="col-sm-6 col-md-6 col-xs-12">
                    <div class="banner-home-inner ">
                        <a href="#">
                            <img src="https://www.fahasa.com/media/wysiwyg/Thang-12-2018/TIPS-596x186-2.png" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-sm-3 col-md-3 col-xs-6 m-pad-l-5">
                    <div class="banner-home-inner ">
                        <a href="#">
                            <img src="https://www.fahasa.com/media/wysiwyg/Thang-12-2018/TIPS-270x186-2.png" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-sm-3 col-md-3 col-xs-6 m-pad-r-5">
                    <div class="banner-home-inner ">
                        <a href="#">
                            <img src="https://www.fahasa.com/media/wysiwyg/Thang-11-2018/Fahasa-Book-Award-270x186.png" alt="">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="content-product-vh">
    <div class="container">
        <div class="row">
            <a href="~/PopularContent/NewestBook/1">
                <h4>Sách mới nhất</h4>
            </a>
            @{
                Html.RenderAction("GetBookByNewest", "PopularContent");
            }
        </div>
    </div>
</div>

<div class="content-product-vh">
    <div class="container">
        <div class="row">
            <a href="~/PopularContent/PopularestBook/1">
                <h4>Sách bán chạy nhất</h4>
            </a>
            @{
                Html.RenderAction("GetBookByPopularest", "PopularContent");
            }
        </div>
    </div>
</div>

<div class="content-product-vh">
    <div class="container">
        <div class="row">
            <a href="~/Books/SearchByCate/1/1">
                <h4>Sách kiếm hiệp</h4>
            </a>
            @{
                Html.RenderAction("SearchByCate", "PopularContent", new { id = 1 });
            }
        </div>
    </div>
</div>

<div class="content-product-vh">
    <div class="container">
        <div class="row">
            <a href="~/Books/SearchByCate/2/1">
                <h4>Sách trinh thám</h4>
            </a>
            @{
                Html.RenderAction("SearchByCate", "PopularContent", new { id = 2 });
            }
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/ajax")
<script>
    function clickModal(id) {
        $("#myModal" + id).modal();
    }
    window.setInterval(function () {
        $("#nextImg").click();
    }, 5000);
</script>

DoAnWeb/Views/Books/SearchByCate.cshtml
@model List<DoAnWeb.Models.Book>

@{
    ViewBag.Title = "SearchByCate";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<link href="~/Content/Effect.css" rel="stylesheet" />
<h4>Kết Quả Tìm Theo Thể Loại @ViewBag.CateName</h4>
<div class="row">
    <div class="col"></div>
    <div class="col-10 row">
        @{
            Html.RenderAction("GetBooksCards", "Books", new { books = Model });
        }
    </div>
    <div class="col"></div>
</div>
<div class="row">
    <div class="col-1">
        @if (ViewBag.PageIndex != 1)
        {
            using (Html.BeginForm())
            {
                int nextPage = ViewBag.PageIndex - 1;
                <input type="hidden" value="@nextPage" name="page" />
                <input type="hidden" value="@ViewBag.SearchKey" name="name" />
                <input type="submit" class="btn btn-dark" value="prev" />
            }
        }
    </div>
    <div class="col-10 text-center">
        @using (Html.BeginForm())
        {
            <input type="number" class="text-body col-1" value="@ViewBag.PageIndex" min="1" name="page" />
            <input type="hidden" value="@ViewBag.SearchKey" name="name" />
            <input type="submit" class="btn btn-dark" value="GO" />
        }
    </div>
    <div class="col-1">
        @if (Model.Count > 0)
        {
            using (Html.BeginForm())
            {
                int nextPage = ViewBag.PageIndex + 1;
                <input type="hidden" value="@nextPage" name="page" />
                <input type="hidden" value="@ViewBag.SearchKey" name="name" />
                <input type="submit" class="btn btn-dark" value="next" />
            }

        }
    </div>
</div>

DoAnWeb/Views/Books/SearchByName.cshtml
@model List<DoAnWeb.Models.Book>

@{
    ViewBag.Title = "SearchByName";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<link href="~/Content/Effect.css" rel="stylesheet" />

<h4>Kết Quả Tìm Theo Từ Khóa "@ViewBag.SearchKey"</h4>
<div class="row">
    <div class="col"></div>
    <div class="col-10 row">
        @{
            Html.RenderAction("GetBooksCards", "Books", new { books = Model });
        }
    </div>
    <div class="col"></div>
</div>
<div class="row">
    <div class="col-1">
        @if (ViewBag.PageIndex != 1)
        {
            using (Html.BeginForm())
            {
                int nextPage = ViewBag.PageIndex - 1;
                <input type="hidden" value="@nextPage" name="page" />
                <input type="hidden" value="@ViewBag.SearchKey" name="name" />
                <input type="submit" class="btn btn-dark" value="prev" />
            }
        }
    </div>
    <div class="col-10 text-center">
        @using (Html.BeginForm())
        {
            <input type="number" class="text-body col-1" value="@ViewBag.PageIndex" min="1" name="page" />
            <input type="hidden" value="@ViewBag.SearchKey" name="name" />
            <input type="submit" class="btn btn-dark" value="GO" />
        }
    </div>
    <div class="col-1">
        @if (Model.Count > 0)
        {
            using (Html.BeginForm())
            {
                int nextPage = ViewBag.PageIndex + 1;
                <input type="hidden" value="@nextPage" name="page" />
                <input type="hidden" value="@ViewBag.SearchKey" name="name" />
                <input type="submit" class="btn btn-dark" value="next" />
            }

        }
    </div>
</div>